/** All blog posts — newest first */
export const BLOG_POSTS = [
  {
    title: "How to Remove Backgrounds for E-commerce Product Photos",
    excerpt:
      "Step-by-step guide to clean white backgrounds that boost conversions on Shopify, Amazon, and Etsy.",
    date: "May 12, 2026",
    slug: "remove-backgrounds-ecommerce-product-photos",
    category: "Background removal",
    readTime: "6 min read",
    toolLink: "/remove-bg",
    image: "/images/remove-bg/product-sneaker-after.jpg",
    imageAlt: "Sneaker product photo with clean background removed for e-commerce listing",
  },
  {
    title: "AI Image Upscaling: When to Use 2× vs 4×",
    excerpt: "Get sharper social posts and print assets without artifacts — choose the right upscale setting.",
    date: "May 8, 2026",
    slug: "ai-image-upscaling-2x-vs-4x",
    category: "Upscale",
    readTime: "5 min read",
    toolLink: "/upscale",
    image: "/images/upscale/product-after-portrait.jpg",
    imageAlt: "Upscaled product image showing sharper detail after AI enhancement",
  },
  {
    title: "Privacy Best Practices for Online Image Tools",
    excerpt: "What to look for before uploading sensitive photos to any AI editor online.",
    date: "May 1, 2026",
    slug: "privacy-best-practices-online-image-tools",
    category: "Privacy",
    readTime: "4 min read",
    toolLink: "/privacy",
    image: "/images/remove-bg/portrait-before.jpg",
    imageAlt: "Portrait photo example for safe upload to online AI image tools",
  },
  {
    title: "Portrait Background Removal: Hair & Edge Tips",
    excerpt: "How to get clean cutouts on portraits with fine hair, glasses, and soft edges every time.",
    date: "April 28, 2026",
    slug: "portrait-background-removal-hair-edge-tips",
    category: "Background removal",
    readTime: "5 min read",
    toolLink: "/remove-bg",
    image: "/images/remove-bg/portrait-after.png",
    imageAlt: "Portrait with background removed showing clean hair edges on transparent PNG",
  },
  {
    title: "Blur Background for Professional Portrait Photos",
    excerpt: "Create a DSLR-style depth-of-field look while keeping your subject sharp and natural.",
    date: "April 24, 2026",
    slug: "blur-background-professional-portraits",
    category: "Blur background",
    readTime: "4 min read",
    toolLink: "/blur-background",
    image: "/images/blur-background/portrait-after-real.jpg",
    imageAlt: "Portrait photo with beautifully blurred background using AI depth effect",
  },
  {
    title: "Generate AI Backgrounds for Product Listings",
    excerpt: "Replace plain backdrops with studio, lifestyle, or colored scenes that match your brand.",
    date: "April 20, 2026",
    slug: "generate-ai-backgrounds-product-listings",
    category: "Generate background",
    readTime: "6 min read",
    toolLink: "/generate-background",
    image: "/images/generate-bg/home-pet-after-blue-v3.jpg",
    imageAlt: "Pet photo with AI-generated blue background for creative product-style shots",
  },
  {
    title: "Enhance Image Quality Without Over-Editing",
    excerpt: "Fix lighting, color, and clarity while keeping skin tones and highlights natural.",
    date: "April 16, 2026",
    slug: "enhance-image-quality-without-over-editing",
    category: "Enhance",
    readTime: "5 min read",
    toolLink: "/enhance-image",
    image: "/images/upscale/portrait-after.jpg",
    imageAlt: "Enhanced portrait with improved clarity and balanced lighting",
  },
  {
    title: "Remove Watermarks Safely: What You Need to Know",
    excerpt: "Legal and practical guidance for cleaning your own images — not someone else's work.",
    date: "April 12, 2026",
    slug: "remove-watermarks-safely-legal-guide",
    category: "Watermark",
    readTime: "4 min read",
    toolLink: "/remove-watermark",
    image: "/images/remove-watermark/portrait-after-v5.jpg",
    imageAlt: "Photo after watermark removal showing restored image detail",
  },
  {
    title: "Pet Photo Editing: Fur, Whiskers & Busy Backgrounds",
    excerpt: "Cut out cats and dogs cleanly even when fur blends into grass or furniture.",
    date: "April 8, 2026",
    slug: "pet-photo-editing-fur-backgrounds",
    category: "Background removal",
    readTime: "5 min read",
    toolLink: "/remove-bg",
    image: "/images/remove-bg/pet-after.png",
    imageAlt: "Pet photo with background removed showing detailed fur edges",
  },
  {
    title: "Shopify Product Photos: White vs Transparent PNG",
    excerpt: "Which export format converts better on Shopify themes and marketplace grids.",
    date: "April 4, 2026",
    slug: "shopify-product-photos-white-vs-transparent",
    category: "E-commerce",
    readTime: "4 min read",
    toolLink: "/remove-bg",
    image: "/images/upscale/product-before-portrait.jpg",
    imageAlt: "Product photo prepared for Shopify listing with clean background",
  },
  {
    title: "Social Media Image Sizes After Background Removal",
    excerpt: "Resize cutouts for Instagram, TikTok, and LinkedIn without losing edge quality.",
    date: "March 30, 2026",
    slug: "social-media-image-sizes-after-bg-removal",
    category: "Social media",
    readTime: "5 min read",
    toolLink: "/remove-bg",
    image: "/images/remove-bg/portrait-before.jpg",
    imageAlt: "Portrait prepared for social media after background removal",
  },
  {
    title: "Batch Workflow Tips for Catalog Photography",
    excerpt: "Keep lighting, framing, and export settings consistent across hundreds of SKUs.",
    date: "March 26, 2026",
    slug: "batch-workflow-tips-catalog-photography",
    category: "Workflow",
    readTime: "6 min read",
    toolLink: "/remove-bg",
    image: "/images/remove-bg/product-sneaker-before.jpg",
    imageAlt: "Multiple product photos prepared for catalog background removal workflow",
  },
  {
    title: "Upscale Old Photos for Print & Posters",
    excerpt: "Recover detail from compressed JPEGs before sending files to print vendors.",
    date: "March 22, 2026",
    slug: "upscale-old-photos-for-print-posters",
    category: "Upscale",
    readTime: "5 min read",
    toolLink: "/upscale",
    image: "/images/upscale/pet-after.jpg",
    imageAlt: "Upscaled pet photo with restored fur detail suitable for print",
  },
  {
    title: "Blur Background vs Remove Background: Which to Choose?",
    excerpt: "Compare both tools for headshots, team pages, and lifestyle product shots.",
    date: "March 18, 2026",
    slug: "blur-vs-remove-background-which-to-choose",
    category: "Guides",
    readTime: "4 min read",
    toolLink: "/blur-background",
    image: "/images/blur-background/product-after-real-portrait.jpg",
    imageAlt: "Product photo with blurred background compared to full removal",
  },
  {
    title: "Free Background Remover AI vs Paid Tools",
    excerpt: "How our free tier compares on speed, quality, privacy, and export limits.",
    date: "March 14, 2026",
    slug: "free-background-remover-ai-vs-paid-tools",
    category: "Comparisons",
    readTime: "6 min read",
    toolLink: "/remove-bg",
    image: "/images/generate-bg/home-pet-before-v3.jpg",
    imageAlt: "Before and after example comparing free AI background removal quality",
  },
  {
    title: "Best Background Colors for Passport Photos",
    excerpt: "Official-looking ID photo colors after background removal — white, off-white, and country-specific tips.",
    date: "March 10, 2026",
    slug: "best-background-colors-passport-photos",
    category: "Guides",
    readTime: "5 min read",
    toolLink: "/remove-bg",
    image: "/images/remove-bg/portrait-after.png",
    imageAlt: "Portrait cutout ready for passport-style solid background colors",
  },
  {
    title: "How to Remove Background Without Photoshop",
    excerpt: "Skip expensive desktop software — remove backgrounds online free with AI in your browser.",
    date: "March 6, 2026",
    slug: "remove-background-without-photoshop",
    category: "Guides",
    readTime: "5 min read",
    toolLink: "/remove-bg",
    image: "/images/remove-bg/product-sneaker-after.jpg",
    imageAlt: "Product cutout created without Photoshop using free online AI",
  },
  {
    title: "PNG vs JPG: Which Format Should You Use?",
    excerpt: "Transparency, file size, and quality trade-offs for cutouts, logos, and marketplace photos.",
    date: "March 2, 2026",
    slug: "png-vs-jpg-which-format",
    category: "Guides",
    readTime: "4 min read",
    toolLink: "/remove-bg",
    image: "/images/upscale/product-before-portrait.jpg",
    imageAlt: "Product photo illustrating PNG transparency versus JPG compression",
  },
  {
    title: "Transparent Background Guide",
    excerpt: "What a transparent PNG is, how alpha channels work, and when to use them in design tools.",
    date: "February 26, 2026",
    slug: "transparent-background-guide",
    category: "Guides",
    readTime: "5 min read",
    toolLink: "/remove-bg",
    image: "/images/remove-bg/pet-after.png",
    imageAlt: "Pet cutout on transparent checkerboard background",
  },
  {
    title: "Ecommerce Image Optimization Tips",
    excerpt: "Compress, crop, and cut out product photos so listings load fast and convert better.",
    date: "February 22, 2026",
    slug: "ecommerce-image-optimization",
    category: "E-commerce",
    readTime: "6 min read",
    toolLink: "/remove-bg",
    image: "/images/remove-bg/product-sneaker-before.jpg",
    imageAlt: "Ecommerce product photo prepared for optimization and background removal",
  },
] as const;

export type BlogPost = (typeof BLOG_POSTS)[number];
